# Generated by Django 4.2.20 on 2025-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tandem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="session_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("tandem", "Tandem"),
                    ("correction", "Correction"),
                ],
                max_length=10,
            ),
        ),
    ]
